version: '3'
tasks:
  test:
    cmds:
      - ./vendor/bin/sail artisan migrate
      - ./vendor/bin/sail artisan ide-helper:models --write --reset
      - ./vendor/bin/sail pint
      - ./vendor/bin/sail bin rector process
      - ./vendor/bin/sail bin phpstan
      - ./vendor/bin/sail pest
      - ./vendor/bin/sail pnpm run build
